name: Code Quality Checks

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

permissions:
    contents: read

env:
    OS: ubuntu-latest

jobs:
    prettier:
        runs-on: $OS
        name: Prettier
        steps:
            - name: git-checkout
              uses: actions/checkout@v3

            - name: Install all dependencies
              run: npm ci

            - name: Prettier
              run: npm run format:check

    lint:
        runs-on: $OS
        name: ESLint
        steps:
            - name: git-checkout
              uses: actions/checkout@v3

            - name: Install all dependencies
              run: npm ci

            - name: ESLint
              run: npm run lint
