name: Code Quality Checks

on:
    push:
    pull_request:
        branches:
            - main

permissions:
    contents: read

jobs:
    prettier:
        strategy:
            matrix:
                os: [ubuntu-latest]
        runs-on: ubuntu-latest
        name: Prettier
        steps:
            - name: git-checkout
              uses: actions/checkout@v3

            - name: Install all dependencies
              run: npm ci

            - name: Prettier
              run: npm run format:check

            - name: ESLint
              run: npm run lint
